routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('customer.home');

Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');

Route::post('/admin/login', 'Auth\LoginController@login')->name('admin.login');

Route::get('/customer/login', 'Customer\LoginController@showLoginForm')->name('customer.login');

Route::post('/customer/login', 'Customer\LoginController@login')->name('customer.login');

Route::get('/customer/register', 'Auth\RegisterController@showCustomerRegisterForm')->name('customer.register');

Route::post('/customer/register', 'Auth\RegisterController@createCustomer')->name('customer.register');

Route::get('/home', 'HomeController@index')->name('home');

// Admin
Route::group([
    'middleware' => ['auth:admin', 'web'],
    'namespace' => 'Admin',
    'prefix' => 'admin',
], function () {
    //Route::get('/home', 'HomeController@index')->name('admin.home');
    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/dashboard/sales-graph-data', 'DashboardController@graphData')->name('admin.sales-graph-data');

    Route::get('/profile', 'ProfileController@index')->name('admin.profile');
    Route::put('/update-profile', 'ProfileController@update')->name('admin.update_profile');

    Route::get('/change-password', 'ProfileController@changePassword')->name('admin.change_password');
    Route::put('/update-password', 'ProfileController@updatePassword')->name('admin.update_password');

    Route::get('/customers', 'CustomerController@index')->name('admin.customers');
    Route::get('/customers/{customer}', 'CustomerController@edit')->name('admin.customers.edit');
    Route::put('/customers/{customer}', 'CustomerController@update')->name('admin.customers.update');
    Route::put('/customers/{customer}/update-status', 'CustomerController@updateStatus')->name('admin.customers.updateStatus');
    Route::post('/customers/export', 'CustomerController@export')->name('admin.customers.export');

    Route::put('item-categories/{itemCategory}/update-status', 'ItemCategoryController@updateStatus')->name('admin.item-categories.updateStatus');
    Route::resource('item-categories', 'ItemCategoryController', ['as' => 'admin']);

    Route::put('/users/{user}/update-status', 'UserController@updateStatus')->name('admin.users.updateStatus');
    Route::resource('users', 'UserController', ['as' => 'admin']);

    Route::put('items/{item}/update-status', 'ItemController@updateStatus')->name('admin.items.updateStatus');
    Route::resource('items', 'ItemController', ['as' => 'admin']);

    Route::get('item/{item}/modifiers/create', 'ModifierController@create')->name('admin.modifiers.create');
    Route::post('item/{item}/modifiers/store', 'ModifierController@store')->name('admin.modifiers.store');
    Route::delete('item/{item}/modifiers/{modifier}/destroy', 'ModifierController@destroy')->name('admin.modifiers.destroy');
    Route::get('item/{item}/modifiers/{modifier}/edit', 'ModifierController@edit')->name('admin.modifiers.edit');
    Route::put('item/{item}/modifiers/{modifier}/update', 'ModifierController@update')->name('admin.modifiers.update');


    Route::get('item/{item}/common-modifiers/create', 'CommonModifierController@createToItem')->name('admin.common-modifiers-to-item.create');
    Route::post('item/{item}/common-modifiers/store', 'CommonModifierController@storeToItem')->name('admin.common-modifiers-to-item.store');
    Route::delete('item/{item}/common-modifiers/{itemModifier}/destroy', 'CommonModifierController@destroyToItem')->name('admin.common-modifiers-to-item.destroy');
    Route::get('item/{item}/common-modifiers/{itemModifier}/edit', 'CommonModifierController@editToItem')->name('admin.common-modifiers-to-item.edit');
    Route::put('item/{item}/common-modifiers/{itemModifier}/update', 'CommonModifierController@updateToItem')->name('admin.common-modifiers-to-item.update');


    Route::get('item/{item}/item-size/create', 'ItemSizeController@create')->name('admin.item-size.create');
    Route::post('item/{item}/item-size/store', 'ItemSizeController@store')->name('admin.item-size.store');
    Route::delete('item/{item}/item-size/{size}/destroy', 'ItemSizeController@destroy')->name('admin.item-size.destroy');
    Route::get('item/{item}/item-size/{size}/edit', 'ItemSizeController@edit')->name('admin.item-size.edit');
    Route::put('item/{item}/item-size/{size}/update', 'ItemSizeController@update')->name('admin.item-size.update');

    Route::put('coupons/{coupon}/update-status', 'CouponController@updateStatus')->name('admin.coupons.updateStatus');
    Route::resource('coupons', 'CouponController', ['as' => 'admin']);

    Route::put('cities/{city}/update-status', 'CityController@updateStatus')->name('admin.cities.updateStatus');
    Route::resource('cities', 'CityController', ['as' => 'admin']);

    Route::get('/store-settings', 'StoreSettingsController@index')->name('admin.store-settings');
    Route::put('/store-settings/basic-info', 'StoreSettingsController@updateBasicInfo')->name('admin.store-settings.update-basic-info');
    Route::put('/store-settings/contact-details', 'StoreSettingsController@updateContactDetails')->name('admin.store-settings.update-contact-details');
    Route::put('/store-settings/other-details', 'StoreSettingsController@updateOtherDetails')->name('admin.store-settings.update-other-details');
    Route::put('/store-settings/other-settings', 'StoreSettingsController@updateOtherSettings')->name('admin.store-settings.update-other-settings');

    Route::get('/order-settings', 'OrderSettingsController@index')->name('admin.order-settings');
    Route::put('/order-settings', 'OrderSettingsController@update')->name('admin.order-settings.update');

    Route::get('/working-hours', 'workingHoursController@index')->name('admin.working-hours');
    Route::put('/working-hours', 'workingHoursController@update')->name('admin.working-hours.update');

    Route::get('/social-media', 'SocialMediaController@index')->name('admin.social-medias');
    Route::put('/social-media', 'SocialMediaController@update')->name('admin.social-medias.update');

    Route::get('/email-settings', 'EmailSettingsController@index')->name('admin.email-settings');
    Route::put('/email-settings', 'EmailSettingsController@update')->name('admin.email-settings.update');

    Route::get('/sms-settings', 'SmsSettingsController@index')->name('admin.sms-settings');
    Route::put('/sms-settings', 'SmsSettingsController@update')->name('admin.sms-settings.update');

    Route::get('/payment-settings', 'PaymentSettingsController@index')->name('admin.payment-settings');
    Route::put('/payment-settings/update-payment-settings', 'PaymentSettingsController@updatePaymentSettings')->name('admin.payment-settings.update-payment-settings');
    Route::put('/payment-settings/update-stripe-settings', 'PaymentSettingsController@updateStripeSettings')->name('admin.payment-settings.update-stripe-settings');
    Route::put('/payment-settings/update-braintree-settings', 'PaymentSettingsController@updateBraintreeSettings')->name('admin.payment-settings.update-braintree-settings');
    Route::put('/payment-settings/update-paypal-settings', 'PaymentSettingsController@updatePaypalSettings')->name('admin.payment-settings.update-paypal-settings');

    Route::put('faqs/{faq}/update-status', 'FaqController@updateStatus')->name('admin.faqs.updateStatus');
    Route::resource('faqs', 'FaqController', ['as' => 'admin']);

    Route::put('reviews/{review}/update-status', 'ReviewController@updateStatus')->name('admin.reviews.updateStatus');
    Route::get('/reviews', 'ReviewController@index')->name('admin.reviews');
    Route::get('/reviews/{review}', 'ReviewController@edit')->name('admin.reviews.edit');
    Route::put('/reviews/{review}', 'ReviewController@update')->name('admin.reviews.update');
    Route::delete('/reviews/{review}', 'ReviewController@destroy')->name('admin.reviews.destroy');

    Route::put('reservations/{reservation}/update-status', 'ReservationController@updateStatus')->name('admin.reservations.updateStatus');
    Route::get('/reservations', 'ReservationController@index')->name('admin.reservations');
    Route::get('/reservations/{reservation}', 'ReservationController@edit')->name('admin.reservations.edit');
    Route::put('/reservations/{reservation}', 'ReservationController@update')->name('admin.reservations.update');
    Route::delete('/reservation/{reservation}', 'ReservationController@destroy')->name('admin.reservations.destroy');

    Route::resource('zones', 'DeliveryZoneController', ['as' => 'admin']);

    Route::get('zones/{zone}/custome-delivey-fee', 'DeliveryZoneController@getCustomeDeliveryFee')->name('admin.zones.custome-delivey-fee');
    Route::post('zones/{zone}/custome-delivey-fee/create', 'DeliveryZoneController@storeCustomeDeliveryFee')->name('admin.zones.custome-delivey-fee.create');

    Route::put('orders/{order}/update-status', 'OrderController@updateStatus')->name('admin.orders.updateStatus');
    Route::get('/orders', 'OrderController@index')->name('admin.orders');
    Route::get('/order/{order}', 'OrderController@edit')->name('admin.orders.edit');
    Route::put('/order/{order}', 'OrderController@update')->name('admin.orders.update');
    Route::delete('/order/{order}', 'OrderController@destroy')->name('admin.orders.destroy');
    Route::get('/orders/{order}/invoice', 'OrderController@getReceipt')->name('admin.orders.invoice');

    Route::resource('common-modifiers', 'CommonModifierController', ['as' => 'admin']);
});

// Customer

app/Models/ItemCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ItemCategory extends Model
{
    public $fillable = [
        'name',
        'description',
        'image',
        'status',
        'start_showing_menu_at',
        'stop_showing_menu_at',
    ];

    public function items()
    {
        return $this->hasMany('App\Models\Item', 'category_id');
    }

    public function isActive()
    {
        return 1 == $this->status;
    }

    public function scopeActive()
    {
        $this->where('status', 1);
    }
}

app/Http/Controllers/Admin/ItemCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\ItemCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\ItemCategoryService;
use App\Http\Requests\ItemCategoryForm;

class ItemCategoryController extends Controller
{
    public function __construct(ItemCategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index()
    {
        return view('admin.item-category.index', [
            'categories' => ItemCategory::orderBy('id', 'desc')->get(),
        ]);
    }

    public function create()
    {
        return view('admin.item-category.create');
    }

    public function store(ItemCategoryForm $request)
    {
        return $this->categoryService->store($request);
    }

    public function edit(ItemCategory $itemCategory)
    {
        return view('admin.item-category.edit', [
            'category' => $itemCategory,
        ]);
    }

    public function update(ItemCategoryForm $request, ItemCategory $itemCategory)
    {
        return $this->categoryService->update($request, $itemCategory);
    }

    public function updateStatus(Request $request, ItemCategory $itemCategory)
    {
        $validatedData = $request->validate([
            'status' => 'required|in:1,0',
        ]);

        $itemCategory->update($validatedData);

        return response()->json(['status' => 'success']);
    }

    public function destroy(ItemCategory $itemCategory)
    {
        $itemCategory->delete();

        flash('Well Done! Item category deleted successfully', 'success');

        return redirect()->route('admin.item-categories.index');
    }
}

app/Http/Controllers/Api/v1/ItemCategoryController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Models\Item;
use App\Models\ItemCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\ItemCollection;
use App\Http\Resources\ItemCategoryCollection;

class ItemCategoryController extends Controller
{
    public function index(Request $request)
    {
        return new ItemCategoryCollection(ItemCategory::active()->get());
    }

    public function show(Request $request, $category)
    {
        $category = ItemCategory::where('id', $category)->first();

        if (empty($category)) {
            return response()->json([
                'status' => 'error',
                'data' => [
                    'message' => 'category not found',
                ],
            ]);
        }

        return new ItemCollection(Item::active()->where('category_id', $category->id)->get());
    }
}

resources/views/admin/item-category/create.blade.php
@extends('layouts.admin')
@section('title', 'Cuisines')

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
	<li class="breadcrumb-item"><a href="{{ route('admin.item-categories.index') }}">Cuisines</a></li>
	<li class="breadcrumb-item active">Create Cuisine</li>
</ol>
@endsection

@section('content')
<div class="row">
	<div class="col-lg-12">
		<!-- Horizontal Form -->
		<div class="card card-default">
			<div class="card-header">
				<h3 class="card-title">{{ __('Create Cuisine') }}</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form class="form-horizontal" method="POST" action="{{ route('admin.item-categories.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Name') }}</label>
								<div class="col-sm-12">
									<input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}">
									@if ($errors->has('name'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('name') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Description') }}</label>
								<div class="col-sm-12">
									<textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" rows="9">{{ old('description') }}</textarea>
									@if ($errors->has('description'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('description') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<img class="img-fluid mb-3 ml-2" width="50%" height="50%" id="image_upload_preview" src="{{ asset('images/default.png') }}"
								alt="Photo">
							</div>
							<small class="ml-2">Please upload an image with 400*300 ratio for better results</small>
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Image') }}</label>
								<div class="col-sm-12">
									<div class="upload-btn-wrapper">
										<button class="upload-btn">Upload a file</button>
										<input type="file" name="image" id="image_upload" class="form-control {{ $errors->has('image') ? ' is-invalid' : '' }}" />
									</div>
									@if ($errors->has('image'))
									<span class="invalid-feedback" role="alert" style="display:block !important;">
										<strong>{{ $errors->first('image') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Status') }}</label>
								<div class="col-sm-12">
									<select name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}">
										<option value="1">Active</option>
										<option value="0">Inactive</option>
									</select>
									@if ($errors->has('status'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('status') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Save</button>
				</div>
				<!-- /.card-footer -->
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/item-category/edit.blade.php
@extends('layouts.admin')
@section('title', 'Cuisines')

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
	<li class="breadcrumb-item"><a href="{{ route('admin.item-categories.index') }}">Cuisines</a></li>
	<li class="breadcrumb-item active">Edit Cuisine</li>
</ol>
@endsection

@section('content')
<div class="row">
	<div class="col-lg-12">
		<!-- Horizontal Form -->
		<div class="card card-default">
			<div class="card-header">
				<h3 class="card-title">{{ __('Edit Cuisine') }}</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form class="form-horizontal" method="POST" action="{{ route('admin.item-categories.update',[$category]) }}" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Name') }}</label>
								<div class="col-sm-12">
									<input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name',$category->name) }}">
									@if ($errors->has('name'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('name') }}</strong>
									</span>
									@endif
								</div>
							</div>
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Description') }}</label>
								<div class="col-sm-12">
									<textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" rows="9">{{ old('description',$category->description) }}</textarea>
									@if ($errors->has('description'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('description') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group ">
								<img class="img-fluid mb-3 ml-2" width="50%" height="50%" id="image_upload_preview" src="{{ asset('storage/'.$category->image) }}"
								alt="Photo">
							</div>
							<small class="ml-2">Please upload an image with 400*300 ratio for better results</small>
							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Image') }}</label>
								<div class="col-sm-12">
									<div class="upload-btn-wrapper">
										<button class="upload-btn">Upload a file</button>
										<input type="file" name="image" id="image_upload" class="form-control {{ $errors->has('image') ? ' is-invalid' : '' }}" />
									</div>
									@if ($errors->has('image'))
									<span class="invalid-feedback" role="alert" style="display:block !important;">
										<strong>{{ $errors->first('image') }}</strong>
									</span>
									@endif
								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-4 control-label">{{ __('Status') }}</label>
								<div class="col-sm-12">
									<select name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}">
										<option value="1" {{ old('status',$category->status)==1?'selected':'' }}>Active</option>
										<option value="0" {{ old('status',$category->status)==0?'selected':'' }}>Inactive</option>
									</select>
									@if ($errors->has('status'))
									<span class="invalid-feedback" role="alert">
										<strong>{{ $errors->first('status') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Save</button>
				</div>
				<!-- /.card-footer -->
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/item-category/index.blade.php
@extends('layouts.admin')
@section('title', 'Cuisines')


@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ __("Dashboard") }}</a></li>
	<li class="breadcrumb-item active">{{ __("Cuisines") }}</li>
</ol>
@endsection

@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">{{ __("Cuisines") }}</h3>
				<div class="card-tools"><a href="{{ route('admin.item-categories.create') }}" class="btn btn-primary btn-sm"><i
					class="fa fa-plus mr-1"></i>Add New Cuisine</a></div>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered table-striped datatable">
							<thead>
								<tr>
									<th width="20%">{{ __("Name") }}</th>
									<th>{{ __("Description") }}</th>
									<th width="5%">{{ __("Enable/Disable") }}</th>
									<th width="5%">{{ __("Action") }}</th>
								</tr>
							</thead>
							<tbody>

								@forelse($categories as $key => $category)
								<tr>
									<td>{{$category->name}}</td>
									<td>{{$category->description}}</td>
									<td>
										<div class="form-group">
											
											<div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
												<input type="checkbox" class="custom-control-input status-toggle" status-data="{{ $category->id }}" status-url="admin.item-categories.updateStatus" id="customSwitch-{{$key}}" {{$category->isActive()?'checked':''}}>
												<label class="custom-control-label" for="customSwitch-{{$key}}"></label>
											</div>

										</div>
									</td>
									<td><a href="{{route('admin.item-categories.edit',[$category])}}" data-toggle="tooltip" title="Edit"><i
										class="fas fa-edit mr-3"></i></a>
										<a href="#" class="delete-btn" delete-url="{{ route('admin.item-categories.destroy',[$category]) }}" data-toggle="modal" data-target="#modal-delete" title="Delete"><i
											class="fas fa-trash"></i></a>
										</td>
									</td>
								</tr>

								@empty
								<tr>
									<td colspan="4">No records found</td>
								</tr>
								@endforelse

								<tfoot>
								</tfoot>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		@endsection