routes/web.php
    Route::post('item/{item}/modifiers/store', 'ModifierController@store')->name('admin.modifiers.store');
    Route::delete('item/{item}/modifiers/{modifier}/destroy', 'ModifierController@destroy')->name('admin.modifiers.destroy');
    Route::get('item/{item}/modifiers/{modifier}/edit', 'ModifierController@edit')->name('admin.modifiers.edit');
    Route::put('item/{item}/modifiers/{modifier}/update', 'ModifierController@update')->name('admin.modifiers.update');


    Route::get('item/{item}/common-modifiers/create', 'CommonModifierController@createToItem')->name('admin.common-modifiers-to-item.create');
    Route::post('item/{item}/common-modifiers/store', 'CommonModifierController@storeToItem')->name('admin.common-modifiers-to-item.store');
    Route::delete('item/{item}/common-modifiers/{itemModifier}/destroy', 'CommonModifierController@destroyToItem')->name('admin.common-modifiers-to-item.destroy');
    Route::get('item/{item}/common-modifiers/{itemModifier}/edit', 'CommonModifierController@editToItem')->name('admin.common-modifiers-to-item.edit');
    Route::put('item/{item}/common-modifiers/{itemModifier}/update', 'CommonModifierController@updateToItem')->name('admin.common-modifiers-to-item.update');


    Route::get('item/{item}/item-size/create', 'ItemSizeController@create')->name('admin.item-size.create');
    Route::post('item/{item}/item-size/store', 'ItemSizeController@store')->name('admin.item-size.store');
    Route::delete('item/{item}/item-size/{size}/destroy', 'ItemSizeController@destroy')->name('admin.item-size.destroy');
    Route::get('item/{item}/item-size/{size}/edit', 'ItemSizeController@edit')->name('admin.item-size.edit');
    Route::put('item/{item}/item-size/{size}/update', 'ItemSizeController@update')->name('admin.item-size.update');

    Route::put('coupons/{coupon}/update-status', 'CouponController@updateStatus')->name('admin.coupons.updateStatus');
    Route::resource('coupons', 'CouponController', ['as' => 'admin']);

    Route::put('cities/{city}/update-status', 'CityController@updateStatus')->name('admin.cities.updateStatus');
    Route::resource('cities', 'CityController', ['as' => 'admin']);

    Route::get('/store-settings', 'StoreSettingsController@index')->name('admin.store-settings');
    Route::put('/store-settings/basic-info', 'StoreSettingsController@updateBasicInfo')->name('admin.store-settings.update-basic-info');
    Route::put('/store-settings/contact-details', 'StoreSettingsController@updateContactDetails')->name('admin.store-settings.update-contact-details');
    Route::put('/store-settings/other-details', 'StoreSettingsController@updateOtherDetails')->name('admin.store-settings.update-other-details');
    Route::put('/store-settings/other-settings', 'StoreSettingsController@updateOtherSettings')->name('admin.store-settings.update-other-settings');

    Route::get('/order-settings', 'OrderSettingsController@index')->name('admin.order-settings');
    Route::put('/order-settings', 'OrderSettingsController@update')->name('admin.order-settings.update');

    Route::get('/working-hours', 'workingHoursController@index')->name('admin.working-hours');
    Route::put('/working-hours', 'workingHoursController@update')->name('admin.working-hours.update');

    Route::get('/social-media', 'SocialMediaController@index')->name('admin.social-medias');
    Route::put('/social-media', 'SocialMediaController@update')->name('admin.social-medias.update');

    Route::get('/email-settings', 'EmailSettingsController@index')->name('admin.email-settings');
    Route::put('/email-settings', 'EmailSettingsController@update')->name('admin.email-settings.update');

    Route::get('/sms-settings', 'SmsSettingsController@index')->name('admin.sms-settings');
    Route::put('/sms-settings', 'SmsSettingsController@update')->name('admin.sms-settings.update');

    Route::get('/payment-settings', 'PaymentSettingsController@index')->name('admin.payment-settings');
    Route::put('/payment-settings/update-payment-settings', 'PaymentSettingsController@updatePaymentSettings')->name('admin.payment-settings.update-payment-settings');
    Route::put('/payment-settings/update-stripe-settings', 'PaymentSettingsController@updateStripeSettings')->name('admin.payment-settings.update-stripe-settings');
    Route::put('/payment-settings/update-braintree-settings', 'PaymentSettingsController@updateBraintreeSettings')->name('admin.payment-settings.update-braintree-settings');
    Route::put('/payment-settings/update-paypal-settings', 'PaymentSettingsController@updatePaypalSettings')->name('admin.payment-settings.update-paypal-settings');

    Route::put('faqs/{faq}/update-status', 'FaqController@updateStatus')->name('admin.faqs.updateStatus');
    Route::resource('faqs', 'FaqController', ['as' => 'admin']);

    Route::put('reviews/{review}/update-status', 'ReviewController@updateStatus')->name('admin.reviews.updateStatus');
    Route::get('/reviews', 'ReviewController@index')->name('admin.reviews');
    Route::get('/reviews/{review}', 'ReviewController@edit')->name('admin.reviews.edit');
    Route::put('/reviews/{review}', 'ReviewController@update')->name('admin.reviews.update');
    Route::delete('/reviews/{review}', 'ReviewController@destroy')->name('admin.reviews.destroy');

    Route::put('reservations/{reservation}/update-status', 'ReservationController@updateStatus')->name('admin.reservations.updateStatus');
    Route::get('/reservations', 'ReservationController@index')->name('admin.reservations');
    Route::get('/reservations/{reservation}', 'ReservationController@edit')->name('admin.reservations.edit');
    Route::put('/reservations/{reservation}', 'ReservationController@update')->name('admin.reservations.update');
    Route::delete('/reservation/{reservation}', 'ReservationController@destroy')->name('admin.reservations.destroy');

    Route::resource('zones', 'DeliveryZoneController', ['as' => 'admin']);

    Route::get('zones/{zone}/custome-delivey-fee', 'DeliveryZoneController@getCustomeDeliveryFee')->name('admin.zones.custome-delivey-fee');
    Route::post('zones/{zone}/custome-delivey-fee/create', 'DeliveryZoneController@storeCustomeDeliveryFee')->name('admin.zones.custome-delivey-fee.create');

    Route::put('orders/{order}/update-status', 'OrderController@updateStatus')->name('admin.orders.updateStatus');
    Route::get('/orders', 'OrderController@index')->name('admin.orders');
    Route::get('/order/{order}', 'OrderController@edit')->name('admin.orders.edit');
    Route::put('/order/{order}', 'OrderController@update')->name('admin.orders.update');
    Route::delete('/order/{order}', 'OrderController@destroy')->name('admin.orders.destroy');
    Route::get('/orders/{order}/invoice', 'OrderController@getReceipt')->name('admin.orders.invoice');

    Route::resource('common-modifiers', 'CommonModifierController', ['as' => 'admin']);
});

// Customer
Route::group([
    'namespace' => 'Customer',
], function () {
    Route::get('items', 'ItemController@index')->name('items.index');

    Route::get('items/{item}', 'ItemController@show')->name('items.show');

    Route::get('cart/items', 'CartController@index')->name('customer.cart.index');

    Route::post('cart/items/{item}/update', 'CartController@update')->name('customer.cart.update');

    Route::post('cart/{cart}/item/delete', 'CartController@delete')->name('customer.cart-item.delete');

    Route::post('cart/{token}/update-quantity', 'CartController@updateQuantity')->name('customer.cart.item.update-quantity');

    Route::post('cart/{token}/apply-coupon', 'CartController@applyCoupon')->name('cart.apply-coupon');
    Route::post('cart/{token}/remove-coupon', 'CartController@removeCoupon')->name('cart.remove-coupon');

    Route::get('order/{order}/show', 'OrderController@show')->name('customer.order.show');

    Route::get('cart/proceed-checkout', 'CartController@proceed')->name('customer.cart.proceed');

    Route::post('cart/checkout', 'CartController@checkout')->name('customer.cart.checkout');

    Route::post('cart/set-location', 'CartController@setLocation')->name('cart.set-location');

    Route::post('cart/stripe/{token}/pay', 'PaymentController@stripePayment')->name('cart.stripe.pay');

    Route::post('cart/paypal/{token}/pay', 'PaymentController@paypalPayment')->name('cart.paypal.get-url');

    Route::get('cart/paypal/{token}/success', 'PaymentController@makePaypalPayment')->name('cart.paypal.success');

    Route::get('cart/paypal/{token}/cancel', 'PaymentController@cancelPaypalPayment')->name('cart.paypal.cancel');

    Route::get('order/{order}/confirmation', 'OrderController@confirmation')->name('customer.order.confirmation');

    Route::get('categories/{category}/items', 'ItemController@items')->name('category.items');

    Route::get('reservation/create', 'ReservationController@create')->name('customer.reservation.create');

    Route::post('reserve-table', 'ReservationController@reserveTable')->name('customer.reserve-table');

    Route::get('faq', 'FaqController@index')->name('customer.faq.index');

    Route::post('contact/store', 'ContactController@contact')->name('customer.contact.store');
    Route::get('contact', 'ContactController@index')->name('customer.contact.index');

    Route::get('account', 'AccountController@index')->name('customer.account.index');

    Route::put('account', 'AccountController@update')->name('customer.profile.update');

    Route::post('account', 'AccountController@changePassword')->name('customer.profile.change-password');
    Route::get('forgot-password', 'ForgotPasswordController@forgot')->name('customer.profile.forgot-password');

    Route::post('send-reset-link', 'ForgotPasswordController@sendOtp')->name('customer.password.email');
    Route::post('reset-password', 'ForgotPasswordController@reset')->name('customer.password.reset');

    Route::post('zone/get-by-geo/{longitude}/{latitude}', 'DeliveryZoneController@getByGeo')->name('customer.zones.get-by-geo');

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    public $fillable = [
        'title',
        'description',
        'status',
    ];

    public function scopeActive()
    {
        return $this->where('status', 1);
    }

    public function isActive()
    {
        return 1 == $this->status;
    }
}

app/Http/Controllers/Admin/FaqController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Faq;
use App\Services\FaqService;
use Illuminate\Http\Request;
use App\Http\Requests\FaqForm;
use App\Http\Controllers\Controller;

class FaqController extends Controller
{
    public function __construct(FaqService $faqService)
    {
        $this->faqService = $faqService;
    }

    public function index(Request $request)
    {
        $request->flash();

        return view('admin.faqs.index', [
            'faqs' => $this->faqService->filter($request)->get(),
        ]);
    }

    public function create()
    {
        return view('admin.faqs.add');
    }

    public function store(FaqForm $request)
    {
        return $this->faqService->create($request);
    }

    public function edit(Request $request, Faq $faq)
    {
        return view('admin.faqs.edit', [
            'faq' => $faq,
        ]);
    }

    public function update(FaqForm $request, Faq $faq)
    {
        return $this->faqService->update($request, $faq);
    }

    /**
     * Change faq status.
     *
     * @param \Illuminate\Http\Request $request, Faq $faq
     *
     * @return json array
     */
    public function updateStatus(Request $request, Faq $faq)
    {
        $validatedData = $request->validate([
            'status' => 'required|in:1,0',
        ]);

        $faq->update($validatedData);

        return response()->json(['status' => 'success']);
    }

    public function destroy(Faq $faq)
    {
        $faq->delete();

        flash('FAQ removed successfully.', 'success');

        return redirect()->route('admin.faqs.index');
    }
}

app/Http/Controllers/Api/v1/FaqController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Models\Faq;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\FaqCollection;

class FaqController extends Controller
{
    public function index(Request $request)
    {
        return new FaqCollection(Faq::active()->get());
    }
}

app/Http/Controllers/Customer/FaqController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Models\Faq;
use App\Http\Controllers\Controller;

class FaqController extends Controller
{
    public function index()
    {
        return view('customer.faq.index', [
            'faqs' => Faq::active()->get(),
        ]);
    }
}

resources/views/admin/faqs/add.blade.php
@extends('layouts.admin')
@section('title', 'Faq')

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ __("Dashboard") }}</a></li>
	<li class="breadcrumb-item"><a href="{{ route('admin.faqs.index') }}">{{ __("Faq") }}</a></li>
	<li class="breadcrumb-item active">{{ __("Add Faq") }}</li>
</ol>
@endsection

@section('content')

<div class="container-fluid">
	<div class="">
		<!-- Horizontal Form -->
		<div class="card card-default">
			<div class="card-header">
				<h3 class="card-title">Add Faq</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form class="form-horizontal" method="post" action="{{ route('admin.faqs.store') }}">
				@csrf
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-4 control-label">Title</label>
								<div class="col-sm-12">
									<input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" autocomplete="off">

									@if ($errors->has('title'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('title') }}</strong>
									</span>
									@endif

								</div>
							</div>
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-4 control-label">Description</label>
								<div class="col-sm-12">
									<textarea id="" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description') }}" rows="10">{{ old('description') }}</textarea>

									@if ($errors->has('description'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('description') }}</strong>
									</span>
									@endif

								</div>
							</div>
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-4 control-label">Status</label>
								<div class="col-sm-12">
									<select name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}">
										<option {{ old('status')==1?'selected':'' }} value="1">Active</option>
										<option {{ old('status')!=1?'selected':'' }} value="0">Inactive</option>
									</select>
									@if ($errors->has('status'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('status') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Update</button>
				</div>
				<!-- /.card-footer -->
			</form>
		</div>
	</div>
</div>

@endsection

resources/views/admin/faqs/edit.blade.php
@extends('layouts.admin')
@section('title', 'Faq')

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ __("Dashboard") }}</a></li>
	<li class="breadcrumb-item"><a href="{{ route('admin.faqs.index') }}">{{ __("Faqs") }}</a></li>
	<li class="breadcrumb-item active">{{ __("Edit Faq") }}</li>
</ol>
@endsection

@section('content')

<div class="container-fluid">
	<div class="">
		<!-- Horizontal Form -->
		<div class="card card-default">
			<div class="card-header">
				<h3 class="card-title">Edit Faq</h3>
			</div>
			<!-- /.card-header -->
			<!-- form start -->
			<form class="form-horizontal" method="post" action="{{ route('admin.faqs.update', $faq) }}">
				@csrf
				<input type="hidden" name="_method" value="PUT">
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-4 control-label">Title</label>
								<div class="col-sm-12">
									<input type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title', $faq->title) }}" autocomplete="off">

									@if ($errors->has('title'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('title') }}</strong>
									</span>
									@endif

								</div>
							</div>
							<div class="form-group">
								<label for="inputEmail3" class="col-sm-4 control-label">Description</label>
								<div class="col-sm-12">
									<textarea id="" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" value="{{ old('description', $faq->description) }}" rows="10">{{ old('description', $faq->description) }}</textarea>

									@if ($errors->has('description'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('description') }}</strong>
									</span>
									@endif

								</div>
							</div>
							<div class="form-group">
								<label for="inputPassword3" class="col-sm-4 control-label">Status</label>
								<div class="col-sm-12">
									<select name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}">
										<option {{ old('status', $faq->status)==1?'selected':'' }} value="1">Active</option>
										<option {{ old('status', $faq->status)!=1?'selected':'' }} value="0">Inactive</option>
									</select>
									@if ($errors->has('status'))
									<span class="invalid-feedback" style="display: block !important;" role="alert">
										<strong>{{ $errors->first('status') }}</strong>
									</span>
									@endif
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.card-body -->
				<div class="card-footer">
					<button type="submit" class="btn btn-success">Update</button>
				</div>
				<!-- /.card-footer -->
			</form>
		</div>
	</div>
</div>

@endsection

resources/views/admin/faqs/index.blade.php
@extends('layouts.admin')
@section('title', 'Faqs')

@section('breadcrumb')
<ol class="breadcrumb float-sm-right">
	<li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">{{ __("Dashboard") }}</a></li>
	<li class="breadcrumb-item active">{{ __("Faqs") }}</li>
</ol>
@endsection

@section('content')

<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Faqs</h3>
				<div class="card-tools row">	

					<div class="mr-2">
						<form method="get" action="{{route('admin.faqs.index')}}">
							<div class="input-group mb-3">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="fas fa-search"></i></span>
								</div>
								<input type="text" placeholder="{{ __('Search') }}" name="search" autocomplete="off" value="{{ old('search') }}" class="form-control">
								<input type="submit" style="display: none;">
							</div>
						</form>
					</div>

					<div class="pull-right">
						<a href="{{ route('admin.faqs.create') }}" class="btn btn-primary btn-sm"><i class="fa fa-plus mr-1"></i>Add New Faq</a>
					</div>

				</div>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				<div class="table-responsive">
					<table id="example1" class="table table-bordered table-striped">
						<thead>
							<tr>
								<th>{{ __("Title") }}</th>
								<th>{{ __("Description") }}</th>
								<th width="5%">{{ __("Enable/Disable") }}</th>
								<th>{{ __("Action") }}</th>
							</tr>
						</thead>
						<tbody>

							@forelse($faqs as $key => $faq)
							
							<tr role="row" class="odd">
								<td width="20%" class="sorting_1">{{ $faq->title }}</td>
								<td>{{ $faq->description }}</td>
								<td>
									<div class="form-group">
										<div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
											<input type="checkbox" class="custom-control-input js-user-status status-toggle" status-data="{{  $faq->id  }}" status-url="admin.faqs.updateStatus" id="customSwitch-{{$key}}" {{$faq->isActive()?'checked':''}}>
											<label class="custom-control-label" for="customSwitch-{{$key}}"></label>
										</div>
									</div>
								</td>
								<td>
									<a href="{{route('admin.faqs.edit',[$faq])}}" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>

									<a href="javascript:void(0);" data-toggle="tooltip" title="Delete" class="js-delete-user"><i class="fas fa-trash"></i></a>
									<form method="post" action="{{route('admin.faqs.destroy', $faq)}}" class="js-form-delete-user">
										@csrf
										<input type="hidden" name="_method" value="DELETE">
									</form>	


								</td>
							</tr>

							@empty
							<p>Sorry No faqs found!</p>
							@endforelse

						</tbody>
					</table>
				</div>
			</div>
		</div>
		<!-- /.card-body -->
	</div>
</div>	

@endsection